// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepository(arg1) {
  return window['go']['main']['App']['AddRepository'](arg1);
}

export function CancelRebase(arg1) {
  return window['go']['main']['App']['CancelRebase'](arg1);
}

export function GetPRCIStatus(arg1, arg2) {
  return window['go']['main']['App']['GetPRCIStatus'](arg1, arg2);
}

export function GetPullRequests() {
  return window['go']['main']['App']['GetPullRequests']();
}

export function GetRepositories() {
  return window['go']['main']['App']['GetRepositories']();
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function LoginGitHub() {
  return window['go']['main']['App']['LoginGitHub']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RebasePRs(arg1) {
  return window['go']['main']['App']['RebasePRs'](arg1);
}

export function RemoveRepository(arg1) {
  return window['go']['main']['App']['RemoveRepository'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
