// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddRepository(arg1:string):Promise<models.Repository>;

export function CancelRebase(arg1:string):Promise<void>;

export function GetPRCIStatus(arg1:string,arg2:string):Promise<string>;

export function GetPullRequests():Promise<Array<models.PullRequest>>;

export function GetRemotes(arg1:string):Promise<Array<string>>;

export function GetRepositories():Promise<Array<models.Repository>>;

export function GetSession():Promise<models.Session>;

export function GetSettings():Promise<models.Settings>;

export function LoginGitHub():Promise<void>;

export function Logout():Promise<void>;

export function RebasePRs(arg1:Array<models.RebaseRequest>):Promise<void>;

export function RemoveRepository(arg1:string):Promise<void>;

export function SaveSettings(arg1:models.Settings):Promise<void>;

export function SetBranchTracking(arg1:string,arg2:string,arg3:string):Promise<void>;
